inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'bin/*'
Style/SymbolArray:
  Exclude:
    - Gemfile

Style/Documentation:
  Exclude:
    - app/helpers/*.rb
    - app/mailers/*.rb
    - app/models/application_record.rb
