language: ruby
rvm: 2.5.0
cache: bundler

services:
  - mysql

addons:
  ssh_known_hosts: aaronjsutton.com

install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

script:
  - brakeman -f html -o /tmp/report.html
  - rubocop -f html -o /tmp/rubocop.html
  - bundle exec rake spec

notifications:
  email:
    - ajsutton.dev@gmail.com

deploy:
  - provider: script
    skip_cleanup: true  
    script: bin/reports.sh
    on:
      branch: rewrite
