language: ruby
rvm: 2.5.0
cache: bundler

services:
  - mysql

env:
  global:
    - REMOTE_DIR=/var/www/darkspeed-dev
    - REMOTE_USER=darkspeed
    - REMOTE_HOST=104.236.114.192

install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

script:
  - bundle exec rake spec
  - brakeman -f html -o /tmp/report.html

notifications:
  email:
    - ajsutton.dev@gmail.com
