language: ruby
rvm: 2.5.0
cache: bundler

services:
  - mysql

addons:
  ssh_known_hosts: aaronjsutton.com

install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

script:
  - bundle exec rake spec
  - brakeman -f html -o /tmp/report.html

notifications:
  email:
    - ajsutton.dev@gmail.com

deploy:
  skip_cleanup: true
  provider: script
  script:
    # Upload Brakeman Report
    - rsync -r --delete-after --quiet /tmp/report.html darkspeed@aaronjsutton.com:/var/www/darkspeed-dev/security
   on:
      branch: rewrite
