language: ruby
rvm: 2.5.0
cache: bundler

services:
  - mysql

install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

script:
  - bundle exec rake spec

notifications:
  email:
    - ajsutton.dev@gmail.com
