# Define the profiles for operating the DarkSocks server

global:
  cipher: aes-256-ctr
  command: ss-server
  host: <%= ENV["DARKSPEED_HOSTNAME"] %>
  timeout: 600
  plugin: obfs-server
  opts: obfs=http

# Server used to create temporary connections while authenticating
gateway:
  port: 5456
  password: gateway

# Server used by authenticated users
main:
  port: 8008
  password: <%= ENV["DARKSPEED_PASSWORD"] %>
