# Define the profiles for operating the DarkSocks server

cipher: aes-256-ctr
executable: ss-local
host: <%= ENV["DARKSPEED_HOSTNAME"] %>

# Server used to create temporary connections while authenticating
gateway:
  port: 5456
  password: gateway

# Server used by authenticated users
main:
  port: 8008
  password: <%= ENV["DARKSPEED_PASSWORD"] %>
